### ISSUE TITLE
Text position for page number cannot be adjusted when facet_grid_paginate is used

### ISSUE THREAD

**Issue by mmrinconh** [kwstat/pagenum#1]
Hi, I want to change the default just=c(bottom, left) to a different just values but it does not work
` print(ggplot(compGF4plot,aes(Complexity,GoodnessOfFit))+geom_point()+theme_bw()+labs(title="Figure S1")+
    facet_wrap_paginate(facets = 'stock', scales="free",nrow = 3, ncol = 3, page = i)+ylab("Goodness of fit"))
  pagenum(i, text="Page", just=c('right','bottom'), cex=0.9)
  `
The page number remains in the left bottom.

**Comment by kwstat** [comment]
First, a few tips.  1. Please make your bug-report self-contained and as small as possible. Simulate data, load necessary libraries. Simplify the code 2. Read the package documentation and examples thoroughly.

If I understand, you want the page number in the lower right part of the page.  Note that "just" controls the justification *within the text box*, but you actually control the position of the page number text box with "x" and "y").

Is this what you want?

```{r}
library(ggplot2)
library(pagenum)
dat=data.frame(x=rnorm(100), y=rnorm(100), grp=1:5)
ggplot(dat,aes(x,y))+
        geom_point()
pagenum(2, text="Page", x=.95, y=.05, cex=0.9, just=c('right'))
```

**Comment by mmrinconh** [comment]
Sorry I just missunderstand what "Vertical position of timestamp" means, I though x and y were just about the date and not the page number. But I solved following your suggestion. Thank you kwsat.
